// Shared re-exports for the service layer: zod plus the schema DTOs/entities
// the services validate against, in one place to keep service imports compact.

export type {
  AddAttachmentInput,
  Agent,
  AgentStatus,
  AssignTicketInput,
  Attachment,
  ChangeStatusInput,
  Comment,
  CommentInput,
  CreateInviteInput,
  CreateOrgInput,
  CreateProjectInput,
  CreateTeamInput,
  CreateTicketInput,
  Id,
  Invite,
  InviteMemberInput,
  JoinTenantInput,
  LinkTicketsInput,
  Membership,
  Org,
  Principal,
  Project,
  RegisterAgentInput,
  RemoveAttachmentInput,
  Role,
  Team,
  Ticket,
  TicketLink,
  TicketLinkType,
  TicketStatus,
  UnlinkTicketsInput,
  UpdateTicketInput,
  User,
} from '@rooster/schema'
export {
  addAttachmentInput,
  assignTicketInput,
  changeStatusInput,
  commentInput,
  createInviteInput,
  createOrgInput,
  createProjectInput,
  createTeamInput,
  createTicketInput,
  inviteMemberInput,
  joinTenantInput,
  linkTicketsInput,
  registerAgentInput,
  removeAttachmentInput,
  unlinkTicketsInput,
  updateTicketInput,
} from '@rooster/schema'
export { z } from 'zod'
