// Shared re-exports for the service layer: zod plus the schema DTOs/entities
// the services validate against, in one place to keep service imports compact.

export type {
  AddAttachmentInput,
  Agent,
  AgentStatus,
  AssignTicketInput,
  Attachment,
  ChangeStatusInput,
  Comment,
  CommentInput,
  CreateInviteInput,
  CreateMilestoneInput,
  CreateOrgInput,
  CreateProjectInput,
  CreateTeamInput,
  CreateTenantInput,
  CreateTicketInput,
  Id,
  Invite,
  InviteMemberInput,
  JoinTenantInput,
  LinkTicketsInput,
  Membership,
  Milestone,
  MoveTicketInput,
  Org,
  Principal,
  Project,
  RegisterAgentInput,
  RemoveAttachmentInput,
  Role,
  SetProjectKeyInput,
  Team,
  Ticket,
  TicketLink,
  TicketLinkType,
  TicketStatus,
  UnlinkTicketsInput,
  UpdateTicketInput,
  User,
  Watcher,
  WatchTicketInput,
} from '@rooster/schema'
export {
  addAttachmentInput,
  assignTicketInput,
  changeStatusInput,
  commentInput,
  createInviteInput,
  createMilestoneInput,
  createOrgInput,
  createProjectInput,
  createTeamInput,
  createTenantInput,
  createTicketInput,
  inviteMemberInput,
  joinTenantInput,
  linkTicketsInput,
  moveTicketInput,
  registerAgentInput,
  removeAttachmentInput,
  setProjectKeyInput,
  unlinkTicketsInput,
  updateTicketInput,
  watchTicketInput,
} from '@rooster/schema'
export { z } from 'zod'
